config/routes.rb
require "resque_web"
require 'admin_subdomain'
require "resque"
require 'resque_scheduler'
require 'resque_scheduler/server'

Rails.application.routes.draw do

  #match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request, :via => [:get,:post]
  #match '/oauth/token',         :to => 'oauth#token',         :as => :token, :via => [:get,:post]
  match '/v1/access_token',  :to => 'oauth/oauth#access_token',  :as => :access_token, :via => [:get,:post]
  match '/v1/request_token', :to => 'oauth/oauth#request_token', :as => :request_token, :via => [:post,:get]
  match '/v1/authorize',     :to => 'oauth/oauth#authorize',     :as => :authorize, :via => [:get, :post]
#  match '/v1/oauth',               :to => 'oauth#index',         :as => :oauth, :via => [:get,:post]
  post '/v1/cancel_oauth_handshake', :to => 'oauth/oauth#cancel_oauth_handshake'
  match '/v1/users/me', :to => 'oauth/access#profile', :via => [:get]

  # Oauth client management and vadmin secured behind devise admin
  constraints AdminSubdomain do
    resources :oauth_clients, :controller => "oauth/oauth_clients"
    devise_for :admin_auths, path: '/oauth-mgmt',:skip => [:registerable, :registrations,  :confirmable, :confirmations, :passwords], controllers: {
      sessions: 'oauth/admin_auths/sessions' }
    authenticate :admin_auth do
      require 'resque_scheduler/server'
      mount Vadmin::Engine => '/'
      mount Resque::Server.new, :at => '/veeta-background'
      get "/", to: redirect("/admin", status:302)
    end

  end

  mount MyveetaDomain::Engine => "/easy"


  root 'welcome#index'

  #
  post '/webhooks/inbound/reply', :to => 'webhooks/inbound#reply'
  post '/webhooks/inbound/bounce', :to => 'webhooks/inbound#bounce'
  post '/webhooks/intercom/unsubscribe', :to => 'webhooks/intercom#unsubscribe'


#  namespace :oauth do
#    devise_for :talent_auths, controllers: {
#      sessions: 'oauth/talent_auths/sessions' }
#    devise_for :admin_auths, controllers: {
#      sessions: 'oauth/admin_auths/sessions' }
#  end

  devise_for :recruiter_auths , :skip => [:registerable, :registrations, :passwords], controllers: {
    sessions: 'job_mgmt/recruiter_auths/sessions' }
  devise_for :talent_auths, :path => '', :skip => [:registerable, :registrations], :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: {
    sessions: 'oauth/talent_auths/sessions',
    confirmations: 'api/talent/auth/confirmations',
    passwords: 'api/talent/auth/devise_passwords',
    unlocks: 'api/talent/auth/unlocks' }

  resources :recruiters , controller: 'job_mgmt/recruiters' do
    collection do
      post :recruiter_job
      post :create_job
      post :update_job
    end
  end

  resources :talents, only: [:index], controller: 'job_mgmt/talents' do
    member do
      get :download_cv
    end
  end

  resources :jobs, only: [:disable_job] , controller: 'job_mgmt/jobs' do
    member do
      put :disable_job
    end
  end

  resources :cv_sharing_requests, only: [:edit, :update] , controller: 'job_mgmt/cv_sharing_requests' do
    member do
      get :edit
    end
  end

  #universal functionality introduced to other classes
  concern :validable do
    member do
      put :validate
    end
  end

  concern :validables do
    collection do
      post :validate
    end
  end

  #get '/dl/:file_type/:date_hash/:random_security_hash/:access_security_layer/:basename.:extension', controller: 'api/talent/talents', action: 'avatar'

  namespace :api, defaults: {format: :json} do
    namespace :talent do
      #overwriting controllers of devise with custom controllers
      mount_devise_token_auth_for 'TalentAuth', skip: [:omniauth_callbacks, :confirmable, :confirmations, :unlockable, :unlocks], at: '/auth',
                                  controllers: {
                                      sessions: 'api/talent/auth/sessions',
                                      registrations: 'api/talent/auth/registrations',
                                      passwords: 'api/talent/auth/passwords'
                                  }
      #TODO add rack attack security
      devise_scope :talent_auth do
        post "auth/via_file", to: "auth/registrations#create_via_file"
        post "auth/xing_init", to: "auth/registrations#xing_init"
        post "auth/xing_callback", to: "auth/registrations#xing_callback"
        post "auth/linkedin_init", to: "auth/registrations#linkedin_init"
        post "auth/linkedin_callback", to: "auth/registrations#linkedin_callback"
      end

      #resources :referrers , only: [:get_referrers] do
      #  collection do
      #    get :get_referrers
      #  end
      #end

      resource :jobs, only: [:get_current_openings] do
        collection do
          get :get_current_openings
        end
      end

      get 'sharing', to: 'sharing#index'
      get 'vbsharing', to: 'vb_sharing#index'

      put 'sharing/revoke/:company_id', to: 'sharing#revoke'
      put 'vbsharing/revoke/:client_application_id', to: 'vb_sharing#revoke'
      put 'vbsharing/third_party_data_wiped_out/:client_application_id', to: 'vb_sharing#third_party_data_wiped_out'

      # putting :download to resumes resource did not work...
      get 'resumes/download', to: 'resumes#download'

      resources :companies, only: [:index]
      resources :autosuggestions, only: [:index]

      resources :resumes, except: [:edit, :create], concerns: :validables do
        collection do
          put :share_all
        end

        member do
          put :share
          put :sharing_request
          put :fillin
          get :fillin_from_xing
          get :xingreturn
          get :fillin_from_linkedin
          get :linkedinreturn
        end
      end

      get 'cv_sharing_requests/find_by_ext_id', to: 'cv_sharing_requests#find_by_ext_id'
      resources :cv_sharing_requests, only: [:show]
      resources :jobs, only: [:show] do
        collection do
          get :find_by_ext_id
        end
      end

      namespace :resume do
        resources :educations, except: [:edit], concerns: :validables
        resources :work_experiences, except: [:edit], concerns: :validables
        resources :languages, except: [:edit], concerns: :validables
        resources :skills, except: [:edit], concerns: :validables
        resource  :link, except: [:index, :edit, :destroy], concerns: :validables
        resources :documents, except: [:edit], concerns: :validables
        resource  :about, except: [:index, :edit, :destroy], concerns: :validables
        resources :certifications, except: [:edit], concerns: :validables
        resource :pdf_template_setting, only: [:update], concerns: :validables
        #### MODULES DEACTIVATED FOR NOW - PLEASE CAREFULLY CHECK/IMPLEMENT AUTHORIZATION BEFORE ACTIVATING IT!!!!
        #resources :memberships, except: [:edit], concerns: :validables
        #resources :projects, except: [:edit], concerns: :validables
        #resources :awards, except: [:edit], concerns: :validables
        #resources :publications, except: [:edit], concerns: :validables
      end

      resource :talent, only: [:show, :edit, :update], concerns: :validable do
        #no id of specific objects required, for multiple resources
        collection do
          post :avatar_upload
          delete :avatar_remove
          put :update_locale
        end
      end
      resource :talent_auth, only: [] do
        #specific for certain resource
        member do
          put :email
          put :password
          put :delete
          put :resend_confirmation
        end
      end
      resource :talent_setting, only: [:show, :edit, :update], concerns: :validable
      resources :jobapps, except: [:edit, :destroy], concerns: :validables do
        member do
          put :withdrawn
          put :finish
        end
      end
      resources :cv_sharing_responses, only: [:show, :new, :create, :update, :validate, :finish], concerns: :validables do
        member do
          put :finish
        end
      end
    end

    namespace :freshdesk do
      resources :solutions, only: [:show, :index]
    end
    resources :locales, only: :index
    resources :countries, only: :index
    resources :languages, only: :index

  end

  get '/dl/:file_type/:date_hash/:random_security_hash/:access_security_part/:file_name',:to => 'file_redirect#resource',:file_name => /.*/

end

app/controllers/oauth/access_controller.rb
require 'xing_profile_serializer'

class Oauth::AccessController < Oauth::ApplicationController

  ###
  # No common authorization required, oauth authorization via oauth_required before filter
  ###

  #no devise authentication required for profile action
  before_filter :authenticate_talent_auth!, :except => [:profile]

  #respond_to :json
  before_filter :set_default_response_format

  #ensure that oauth authorization is enforced
  before_filter :oauth_required , :only => [:profile]


  def profile
    # get current veeta button sharing
    vbsc = VeetaButtonSharingConnection.find_by(talent_id: current_token.user.talent.id,client_application_id: current_client_application.id,access_revoked_at: nil)
    if vbsc.nil? #not found
      render json: '{"Message":"No access."}', status: 401
      log_event self, response.body, request, {log: { priority: :high }}
    elsif vbsc.latest_sharing_of_connection.resume && vbsc.latest_sharing_of_connection.resume.deleted? # resume was deleted but not yet synced, create sharing entry with no resume, sync pofile only
      vbs = VeetaButtonSharing.new
      vbs.resume = nil
      vbs.veeta_button_sharing_connection = vbsc
      vbs.save!
      AccessSecurityService.new.establish_sharing vbs, vbsc.talent
      serialize_profile_only vbs
      log_event self, vbs, request, {log: { priority: :medium }}
    elsif vbsc.latest_sharing_of_connection.resume.nil? # resume was deleted, sync pofile only
      AccessSecurityService.new.establish_sharing vbsc.latest_sharing_of_connection, vbsc.talent
      serialize_profile_only vbsc.latest_sharing_of_connection
      log_event self, vbsc, request, {log: { priority: :medium }}
    elsif !vbsc.access_revoked_at.nil? #access was revoked, should never happen, as tokens are invalidated upon revoking access
      render json: '{"Message":"No access."}', status: 401
      log_event self, response.body, request, {log: { priority: :high }}
    else
      # clone the currently shared resume if new version needs to be created
      vbs = vbsc.latest_sharing_of_connection
      clone = Resume::Share.clone(vbs.resume.origin)
      latest = vbs.resume.origin.latest

      # is latest shared version the most recent one?
      if latest.id != vbs.resume.id
        #share the new version
        vbs = VeetaButtonSharing.new
        vbs.resume = latest
        vbs.veeta_button_sharing_connection = vbsc
        AccessSecurityService.new.establish_sharing vbs
        vbs.save!
      end
      vbs.update_column(:last_synced_at, DateTime.now)
      users = []
      users <<  vbs.resume
      log_event self, users, request, {log: { priority: :medium }}
      render json: users, each_serializer: XingProfileSerializer, root: "users", client_application: vbsc.client_application
    end
  end


  def current_user=(user)
      current_talent_auth = user
  end

  def current_user
    current_token.user.talent if current_token && current_token.user
  end

  def current_email
    current_token.user.talent.email if current_token && current_token.user  && current_token.user.talent
  end

  private
    def set_default_response_format
      request.format = :json
    end

    def serialize_profile_only vbs
      fake_resume = Resume.new
      fake_resume.talent =  current_token.user.talent
      vbs.update_column(:last_synced_at, DateTime.now)
      users = []
      users <<  fake_resume
      render json: users, each_serializer: XingProfileSerializer, root: "users", client_application: vbs.veeta_button_sharing_connection.client_application

    end
end

app/controllers/oauth/admin_auths/sessions_controller.rb
  module Oauth
  class AdminAuths::SessionsController < Devise::SessionsController
    include Oauth::BrowserLanguageDetector
    http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD']

    ###
    # No authorization required, override devise controller
    ###

    layout 'admin_auths/admin_auths_layout'

    def after_sign_in_path_for(resource)
      '/'
    end

  # before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # You can put the params you want to permit in the empty array.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.for(:sign_in) << :attribute
    # end
  end
end

app/controllers/oauth/application_controller.rb
module Oauth
  class ApplicationController < ActionController::Base
    include Oauth::BrowserLanguageDetector
    include BaseLogger

    ###
    # No authorization required, base controller
    ###

    alias :current_user :current_talent_auth

    def current_ability
      @current_ability ||= Ability::TalentAbility.new(current_user.talent)
    end

    rescue_from CanCan::AccessDenied do |exception|
      render json: { error: :unauthorized}, status: 403
    end

  end
end

app/controllers/oauth/browser_language_detector.rb
module Oauth
  module BrowserLanguageDetector

    def self.included(base)
        base.before_filter :set_locale
    end

    def set_locale
      I18n.locale = extract_locale_from_accept_language_header

    end

    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end

    private

      def extract_locale_from_accept_language_header
        if !request.env['HTTP_ACCEPT_LANGUAGE'].nil?
          request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
        else
          'en'
        end
      end
  end
end

app/controllers/oauth/oauth_clients_controller.rb
module Oauth
  class OauthClientsController < Oauth::ApplicationController

    ###
    # Authorized admins can manage all client applications, no further authorization required
    ###

    before_filter :authenticate_admin_auth!
    before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]
    before_filter :set_default_response_format
    layout 'layouts/admin_auths/admin_auths_layout'


    def index
      @client_applications = current_user.client_applications
      @tokens = []# current_user.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
    end

    def new
      @client_application = ClientApplication.new
    end

    def create
      @client_application = ClientApplication.new(client_application_params)

      if @client_application.save
        flash[:notice] = "Registered the information successfully"
        redirect_to :action => "show", :id => @client_application.id
      else
        render :action => "new"
      end
    end

    def show
    end

    def edit
    end

    def update
      if @client_application.update_attributes(client_application_params)
        flash[:notice] = "Updated the client information successfully"
        redirect_to :action => "show", :id => @client_application.id
      else
        render :action => "edit"
      end
    end

    def destroy
      @client_application.destroy
      flash[:notice] = "Destroyed the client application registration"
      redirect_to :action => "index"
    end


    def current_user
      return current_admin_auth if current_admin_auth
    end


    private
    def set_default_response_format
      request.format = :html
    end


    def client_application_params
        params[:client_application].permit(:name,:url,:callback_url,:support_url,:delete_user_profile_deep_link,:logo,:webhook_url, :cancel_url,:use_cancel_callback, :contact)
    end

    def get_client_application
      unless @client_application = current_user.client_applications.find(params[:id])
        flash.now[:error] = "Wrong application id"
        raise ActiveRecord::RecordNotFound
      end
    end
  end
end

app/controllers/oauth/talent_auths/sessions_controller.rb
module Oauth

  class TalentAuths::SessionsController < Devise::SessionsController
    include Oauth::BrowserLanguageDetector

    ###
    # No authorization required, override devise controller
    ###

    layout 'talent_auths/talent_auths_layout'

    # check if referer matches with client_application
    before_filter :check_referer, except: [:create, :destroy]


  # before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
#     def new

#     end

    def check_referer
      if session[:client_application_name].blank? || session[:client_application_url].blank? || !request.referer #|| !request.referer.starts_with?(session[:client_application_url])
        render json: '{"Message":"Not found"}', status: 404
        false
      end
    end

    # POST /resource/sign_in
     def create
       #error message
       flash[:custom] = t('devise.failure.invalid')
       super
     end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # You can put the params you want to permit in the empty array.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.for(:sign_in) << :attribute
    # end
  end
end

app/views/oauth/oauth/_no_resumes.html.erb
<div id="no-cv"><%= t("veetabutton.authorize.cvmgmt.empty.text_html",client_application_name: session[:client_application_name], veeta_link:  "#{ENV['TALENT_HOST']}resumes/overview") %></div>
<script>
$("#no-cv a").click(function(e){
  ga('send', 'event', 'link', 'click', 'resume-page', rid);
});
</script>

app/views/oauth/oauth/_popover.erb
<script>

  $('[data-toggle="popover"]').popover({
        html: true,
        trigger: 'manual'
    }).click(function(e) {
        $(this).popover('toggle');
        e.preventDefault();
    });

  $(document).click(function(e) {
      if (!$(e.target).is('.popup-marker')) {
          $('.popup-marker').popover('hide');
      }
  });
</script>

app/views/oauth/oauth/_resume_selection.html.erb
<ul class="list-group">
  <% @resumes.each_with_index do |r, i|  %>
    <li class="list-group-item <%= i==0 ? 'active' : '' %>" data-rid="<%= r.id %>">
      <div class="resume-detail-area">
        <div class="inner">
          <div><%= r.name %></div>
          <div class="small-text"><%= t('veetabutton.authorize.cvmgmt.lastupdate')  %> <%= l(r.updated_at, format: :veeta_button_cv_selection) %></div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/oauth/oauth/authorize.html.erb
			<p class="text-primary lead">
				<%= t('veetabutton.login.subtitle',client_application_name: @token.client_application.name)  %>
			</p>

			<%= bootstrap_form_tag url: authorize_url do |f| %>

			  <%= f.hidden_field :oauth_token, value: @token.token %>
			  <%- if params[:oauth_callback] -%>
			    <%= f.hidden_field "oauth_callback", value: params[:oauth_callback] %>
			  <%- end -%>

			  <div class="resumes-list">
					<% if @resumes.nil? || @resumes.empty? %>
						<%= f.hidden_field "authorize", class: "selected_rid", value: nil %>
						<%= render 'oauth/oauth/no_resumes' %>
					<% else %>
						<%= f.hidden_field "authorize", class: "selected_rid", value: @resumes.first.id %>
						<%= render 'oauth/oauth/resume_selection' %>
					<% end %>
			  </div>

			  <div class="info-area">
			    <%= t('veetabutton.authorize.cvmgmt.text')  %> <a href="<%= ENV['TALENT_HOST'] %>"  target="_blank" class="normal", onclick="javascript:ga('send', 'event', 'link', 'click', 'veeta-website');"><%= t('veetabutton.authorize.cvmgmt.link')  %></a>
				</div>

			  <div class="form-actions">
			    <% unless(session[:cancel_url].nil?) %>
			      <%= link_to(t('veetabutton.login.button.cancel'), "/v1/cancel_oauth_handshake", class: "btn btn-default pull-left",onclick: "javascript:ga('send', 'event', 'button', 'click', 'cancel-authorize');", :method => :post) %>
			    <% end %>

			    <%= f.submit t('veetabutton.login.button.continue') , class: "btn btn-primary pull-right", onclick: "javascript:ga('send', 'event', 'button', 'click', 'authorize');" %>  <!--t('veetabutton.login.button.continue')-->
			  </div>
				<div class="clearfix"></div>

			<% end %>


<script>
  $(".list-group-item").click(function(e){
    rid = $(this).data('rid');
    $(".selected_rid").val(rid);
		ga('send', 'event', 'resumes-list', 'click', 'cv-selection', rid);
  });
</script>

app/views/oauth/oauth/authorize_failure.html.erb
<p class="text-primary lead">
  <%= t('veetabutton.common.error') %><% if @token.client_application.url %> <a href="<%= @token.client_application.url %>"  class="normal" onclick= "javascript:ga('send', 'event', 'link', 'click', 'error-back');"><%= t('veetabutton.common.back') %></a><% end %>
</p>
<script>
		ga('send', 'pageview', 'authoriziation-error-page');
</script>

app/views/oauth/oauth/authorize_success.html.erb
<p class="text-primary lead">
  <%= t('veetabutton.common.success') %>
</p>
<script>
		ga('send', 'pageview', 'authorized-without-callback-page');
</script>

app/views/oauth/oauth/oauth2_authorize.html.erb
<h1>Authorize access to your account</h1>
<p>Would you like to authorize <%= link_to @token.client_application.name,@token.client_application.url %> (<%= link_to @token.client_application.url,@token.client_application.url %>) to access your account?</p>
<%= form_tag authorize_url do %>
  <%= hidden_field_tag "response_type", params[:response_type]%>
  <%= hidden_field_tag "client_id", params[:client_id]%>
  <%= hidden_field_tag "redirect_uri", params[:redirect_uri]%>
  <%= hidden_field_tag "state", params[:state]%>
  <%= hidden_field_tag "scope", params[:scope]%>

<p>
  <%= check_box_tag 'authorize' %> authorize access
</p>
<p>
  <%= submit_tag %>
</p>
<% end %>