config/routes.rb
require "resque_web"
require 'admin_subdomain'
require "resque"
require 'resque_scheduler'
require 'resque_scheduler/server'

Rails.application.routes.draw do

  #match '/oauth/test_request',  :to => 'oauth#test_request',  :as => :test_request, :via => [:get,:post]
  #match '/oauth/token',         :to => 'oauth#token',         :as => :token, :via => [:get,:post]
  match '/v1/access_token',  :to => 'oauth/oauth#access_token',  :as => :access_token, :via => [:get,:post]
  match '/v1/request_token', :to => 'oauth/oauth#request_token', :as => :request_token, :via => [:post,:get]
  match '/v1/authorize',     :to => 'oauth/oauth#authorize',     :as => :authorize, :via => [:get, :post]
#  match '/v1/oauth',               :to => 'oauth#index',         :as => :oauth, :via => [:get,:post]
  post '/v1/cancel_oauth_handshake', :to => 'oauth/oauth#cancel_oauth_handshake'
  match '/v1/users/me', :to => 'oauth/access#profile', :via => [:get]

  # Oauth client management and vadmin secured behind devise admin
  constraints AdminSubdomain do
    resources :oauth_clients, :controller => "oauth/oauth_clients"
    devise_for :admin_auths, path: '/oauth-mgmt',:skip => [:registerable, :registrations,  :confirmable, :confirmations, :passwords], controllers: {
      sessions: 'oauth/admin_auths/sessions' }
    authenticate :admin_auth do
      require 'resque_scheduler/server'
      mount Vadmin::Engine => '/'
      mount Resque::Server.new, :at => '/veeta-background'
      get "/", to: redirect("/admin", status:302)
    end

  end

  mount MyveetaDomain::Engine => "/easy"


  root 'welcome#index'

  #
  post '/webhooks/inbound/reply', :to => 'webhooks/inbound#reply'
  post '/webhooks/inbound/bounce', :to => 'webhooks/inbound#bounce'
  post '/webhooks/intercom/unsubscribe', :to => 'webhooks/intercom#unsubscribe'


#  namespace :oauth do
#    devise_for :talent_auths, controllers: {
#      sessions: 'oauth/talent_auths/sessions' }
#    devise_for :admin_auths, controllers: {
#      sessions: 'oauth/admin_auths/sessions' }
#  end

  devise_for :recruiter_auths , :skip => [:registerable, :registrations, :passwords], controllers: {
    sessions: 'job_mgmt/recruiter_auths/sessions' }
  devise_for :talent_auths, :path => '', :skip => [:registerable, :registrations], :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: {
    sessions: 'oauth/talent_auths/sessions',
    confirmations: 'api/talent/auth/confirmations',
    passwords: 'api/talent/auth/devise_passwords',
    unlocks: 'api/talent/auth/unlocks' }

  resources :recruiters , controller: 'job_mgmt/recruiters' do
    collection do
      post :recruiter_job
      post :create_job
      post :update_job
    end
  end

  resources :talents, only: [:index], controller: 'job_mgmt/talents' do
    member do
      get :download_cv
    end
  end

  resources :jobs, only: [:disable_job] , controller: 'job_mgmt/jobs' do
    member do
      put :disable_job
    end
  end

  resources :cv_sharing_requests, only: [:edit, :update] , controller: 'job_mgmt/cv_sharing_requests' do
    member do
      get :edit
    end
  end

  #universal functionality introduced to other classes
  concern :validable do
    member do
      put :validate
    end
  end

  concern :validables do
    collection do
      post :validate
    end
  end

  #get '/dl/:file_type/:date_hash/:random_security_hash/:access_security_layer/:basename.:extension', controller: 'api/talent/talents', action: 'avatar'

  namespace :api, defaults: {format: :json} do
    namespace :talent do
      #overwriting controllers of devise with custom controllers
      mount_devise_token_auth_for 'TalentAuth', skip: [:omniauth_callbacks, :confirmable, :confirmations, :unlockable, :unlocks], at: '/auth',
                                  controllers: {
                                      sessions: 'api/talent/auth/sessions',
                                      registrations: 'api/talent/auth/registrations',
                                      passwords: 'api/talent/auth/passwords'
                                  }
      #TODO add rack attack security
      devise_scope :talent_auth do
        post "auth/via_file", to: "auth/registrations#create_via_file"
        post "auth/xing_init", to: "auth/registrations#xing_init"
        post "auth/xing_callback", to: "auth/registrations#xing_callback"
        post "auth/linkedin_init", to: "auth/registrations#linkedin_init"
        post "auth/linkedin_callback", to: "auth/registrations#linkedin_callback"
      end

      #resources :referrers , only: [:get_referrers] do
      #  collection do
      #    get :get_referrers
      #  end
      #end

      resource :jobs, only: [:get_current_openings] do
        collection do
          get :get_current_openings
        end
      end

      get 'sharing', to: 'sharing#index'
      get 'vbsharing', to: 'vb_sharing#index'

      put 'sharing/revoke/:company_id', to: 'sharing#revoke'
      put 'vbsharing/revoke/:client_application_id', to: 'vb_sharing#revoke'
      put 'vbsharing/third_party_data_wiped_out/:client_application_id', to: 'vb_sharing#third_party_data_wiped_out'

      # putting :download to resumes resource did not work...
      get 'resumes/download', to: 'resumes#download'

      resources :companies, only: [:index]
      resources :autosuggestions, only: [:index]

      resources :resumes, except: [:edit, :create], concerns: :validables do
        collection do
          put :share_all
        end

        member do
          put :share
          put :sharing_request
          put :fillin
          get :fillin_from_xing
          get :xingreturn
          get :fillin_from_linkedin
          get :linkedinreturn
        end
      end

      get 'cv_sharing_requests/find_by_ext_id', to: 'cv_sharing_requests#find_by_ext_id'
      resources :cv_sharing_requests, only: [:show]
      resources :jobs, only: [:show] do
        collection do
          get :find_by_ext_id
        end
      end

      namespace :resume do
        resources :educations, except: [:edit], concerns: :validables
        resources :work_experiences, except: [:edit], concerns: :validables
        resources :languages, except: [:edit], concerns: :validables
        resources :skills, except: [:edit], concerns: :validables
        resource  :link, except: [:index, :edit, :destroy], concerns: :validables
        resources :documents, except: [:edit], concerns: :validables
        resource  :about, except: [:index, :edit, :destroy], concerns: :validables
        resources :certifications, except: [:edit], concerns: :validables
        resource :pdf_template_setting, only: [:update], concerns: :validables
        #### MODULES DEACTIVATED FOR NOW - PLEASE CAREFULLY CHECK/IMPLEMENT AUTHORIZATION BEFORE ACTIVATING IT!!!!
        #resources :memberships, except: [:edit], concerns: :validables
        #resources :projects, except: [:edit], concerns: :validables
        #resources :awards, except: [:edit], concerns: :validables
        #resources :publications, except: [:edit], concerns: :validables
      end

      resource :talent, only: [:show, :edit, :update], concerns: :validable do
        #no id of specific objects required, for multiple resources
        collection do
          post :avatar_upload
          delete :avatar_remove
          put :update_locale
        end
      end
      resource :talent_auth, only: [] do
        #specific for certain resource
        member do
          put :email
          put :password
          put :delete
          put :resend_confirmation
        end
      end
      resource :talent_setting, only: [:show, :edit, :update], concerns: :validable
      resources :jobapps, except: [:edit, :destroy], concerns: :validables do
        member do
          put :withdrawn
          put :finish
        end
      end
      resources :cv_sharing_responses, only: [:show, :new, :create, :update, :validate, :finish], concerns: :validables do
        member do
          put :finish
        end
      end
    end

    namespace :freshdesk do
      resources :solutions, only: [:show, :index]
    end
    resources :locales, only: :index
    resources :countries, only: :index
    resources :languages, only: :index

  end

  get '/dl/:file_type/:date_hash/:random_security_hash/:access_security_part/:file_name',:to => 'file_redirect#resource',:file_name => /.*/

end

app/controllers/oauth/access_controller.rb
require 'xing_profile_serializer'

class Oauth::AccessController < Oauth::ApplicationController

  ###
  # No common authorization required, oauth authorization via oauth_required before filter
  ###

  #no devise authentication required for profile action
  before_filter :authenticate_talent_auth!, :except => [:profile]

  #respond_to :json
  before_filter :set_default_response_format

  #ensure that oauth authorization is enforced
  before_filter :oauth_required , :only => [:profile]


  def profile
    # get current veeta button sharing
    vbsc = VeetaButtonSharingConnection.find_by(talent_id: current_token.user.talent.id,client_application_id: current_client_application.id,access_revoked_at: nil)
    if vbsc.nil? #not found
      render json: '{"Message":"No access."}', status: 401
      log_event self, response.body, request, {log: { priority: :high }}
    elsif vbsc.latest_sharing_of_connection.resume && vbsc.latest_sharing_of_connection.resume.deleted? # resume was deleted but not yet synced, create sharing entry with no resume, sync pofile only
      vbs = VeetaButtonSharing.new
      vbs.resume = nil
      vbs.veeta_button_sharing_connection = vbsc
      vbs.save!
      AccessSecurityService.new.establish_sharing vbs, vbsc.talent
      serialize_profile_only vbs
      log_event self, vbs, request, {log: { priority: :medium }}
    elsif vbsc.latest_sharing_of_connection.resume.nil? # resume was deleted, sync pofile only
      AccessSecurityService.new.establish_sharing vbsc.latest_sharing_of_connection, vbsc.talent
      serialize_profile_only vbsc.latest_sharing_of_connection
      log_event self, vbsc, request, {log: { priority: :medium }}
    elsif !vbsc.access_revoked_at.nil? #access was revoked, should never happen, as tokens are invalidated upon revoking access
      render json: '{"Message":"No access."}', status: 401
      log_event self, response.body, request, {log: { priority: :high }}
    else
      # clone the currently shared resume if new version needs to be created
      vbs = vbsc.latest_sharing_of_connection
      clone = Resume::Share.clone(vbs.resume.origin)
      latest = vbs.resume.origin.latest

      # is latest shared version the most recent one?
      if latest.id != vbs.resume.id
        #share the new version
        vbs = VeetaButtonSharing.new
        vbs.resume = latest
        vbs.veeta_button_sharing_connection = vbsc
        AccessSecurityService.new.establish_sharing vbs
        vbs.save!
      end
      vbs.update_column(:last_synced_at, DateTime.now)
      users = []
      users <<  vbs.resume
      log_event self, users, request, {log: { priority: :medium }}
      render json: users, each_serializer: XingProfileSerializer, root: "users", client_application: vbsc.client_application
    end
  end


  def current_user=(user)
      current_talent_auth = user
  end

  def current_user
    current_token.user.talent if current_token && current_token.user
  end

  def current_email
    current_token.user.talent.email if current_token && current_token.user  && current_token.user.talent
  end

  private
    def set_default_response_format
      request.format = :json
    end

    def serialize_profile_only vbs
      fake_resume = Resume.new
      fake_resume.talent =  current_token.user.talent
      vbs.update_column(:last_synced_at, DateTime.now)
      users = []
      users <<  fake_resume
      render json: users, each_serializer: XingProfileSerializer, root: "users", client_application: vbs.veeta_button_sharing_connection.client_application

    end
end

app/controllers/oauth/admin_auths/sessions_controller.rb
  module Oauth
  class AdminAuths::SessionsController < Devise::SessionsController
    include Oauth::BrowserLanguageDetector
    http_basic_authenticate_with name: ENV['ADMIN_USERNAME'], password: ENV['ADMIN_PASSWORD']

    ###
    # No authorization required, override devise controller
    ###

    layout 'admin_auths/admin_auths_layout'

    def after_sign_in_path_for(resource)
      '/'
    end

  # before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # You can put the params you want to permit in the empty array.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.for(:sign_in) << :attribute
    # end
  end
end

app/controllers/oauth/application_controller.rb
module Oauth
  class ApplicationController < ActionController::Base
    include Oauth::BrowserLanguageDetector
    include BaseLogger

    ###
    # No authorization required, base controller
    ###

    alias :current_user :current_talent_auth

    def current_ability
      @current_ability ||= Ability::TalentAbility.new(current_user.talent)
    end

    rescue_from CanCan::AccessDenied do |exception|
      render json: { error: :unauthorized}, status: 403
    end

  end
end

app/controllers/oauth/browser_language_detector.rb
module Oauth
  module BrowserLanguageDetector

    def self.included(base)
        base.before_filter :set_locale
    end

    def set_locale
      I18n.locale = extract_locale_from_accept_language_header

    end

    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end

    private

      def extract_locale_from_accept_language_header
        if !request.env['HTTP_ACCEPT_LANGUAGE'].nil?
          request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
        else
          'en'
        end
      end
  end
end

app/controllers/oauth/oauth_clients_controller.rb
module Oauth
  class OauthClientsController < Oauth::ApplicationController

    ###
    # Authorized admins can manage all client applications, no further authorization required
    ###

    before_filter :authenticate_admin_auth!
    before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]
    before_filter :set_default_response_format
    layout 'layouts/admin_auths/admin_auths_layout'


    def index
      @client_applications = current_user.client_applications
      @tokens = []# current_user.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
    end

    def new
      @client_application = ClientApplication.new
    end

    def create
      @client_application = ClientApplication.new(client_application_params)

      if @client_application.save
        flash[:notice] = "Registered the information successfully"
        redirect_to :action => "show", :id => @client_application.id
      else
        render :action => "new"
      end
    end

    def show
    end

    def edit
    end

    def update
      if @client_application.update_attributes(client_application_params)
        flash[:notice] = "Updated the client information successfully"
        redirect_to :action => "show", :id => @client_application.id
      else
        render :action => "edit"
      end
    end

    def destroy
      @client_application.destroy
      flash[:notice] = "Destroyed the client application registration"
      redirect_to :action => "index"
    end


    def current_user
      return current_admin_auth if current_admin_auth
    end


    private
    def set_default_response_format
      request.format = :html
    end


    def client_application_params
        params[:client_application].permit(:name,:url,:callback_url,:support_url,:delete_user_profile_deep_link,:logo,:webhook_url, :cancel_url,:use_cancel_callback, :contact)
    end

    def get_client_application
      unless @client_application = current_user.client_applications.find(params[:id])
        flash.now[:error] = "Wrong application id"
        raise ActiveRecord::RecordNotFound
      end
    end
  end
end

app/controllers/oauth/talent_auths/sessions_controller.rb
module Oauth

  class TalentAuths::SessionsController < Devise::SessionsController
    include Oauth::BrowserLanguageDetector

    ###
    # No authorization required, override devise controller
    ###

    layout 'talent_auths/talent_auths_layout'

    # check if referer matches with client_application
    before_filter :check_referer, except: [:create, :destroy]


  # before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
#     def new

#     end

    def check_referer
      if session[:client_application_name].blank? || session[:client_application_url].blank? || !request.referer #|| !request.referer.starts_with?(session[:client_application_url])
        render json: '{"Message":"Not found"}', status: 404
        false
      end
    end

    # POST /resource/sign_in
     def create
       #error message
       flash[:custom] = t('devise.failure.invalid')
       super
     end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # You can put the params you want to permit in the empty array.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.for(:sign_in) << :attribute
    # end
  end
end

app/views/oauth/oauth_clients/_form.html.erb
<% if @client_application.errors.any? %>
  <ul>
    <% @client_application.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="field">
  <label for="client_application_name">Name*</label><br/>
  <%= f.text_field :name %>
</div>
<div class="field">
  <label for="client_application_url">Main Application URL*</label><br/>
  <%= f.text_field :url %>
</div>
<div class="field">
  <label for="client_application_contact">Contact mail*</label><br/>
  <%= f.text_field :contact %>
</div>
<div class="field">
  <label for="client_application_callback_url">Callback URL</label><br/>
  <%= f.text_field :callback_url %>
</div>
<div class="field">
  <label for="client_application_cancel_url">Cancel URL</label><br/>
  <%= f.text_field :cancel_url %>
</div>
<div class="field">
  <label for="client_application_use_cancel_callback">Use Cancle Callback</label><br/>
  <%= f.check_box :use_cancel_callback %>
</div>

<div class="field">
  <label for="client_application_support_url">Support URL</label><br/>
  <%= f.text_field :support_url %>
</div>
<div class="field">
  <label for="client_application_webhook_url">Webhook URL</label><br/>
  <%= f.text_field :webhook_url %>
</div>
<div class="field">
  <label for="client_application_delete_user_profile_deep_link">Delete third party profile deep link</label><br/>
  <%= f.text_field :delete_user_profile_deep_link %>
</div>
<div class="field">
  <label for="client_application_logo">Logo*</label><br/>
  <%= f.file_field :logo %>
</div>

app/views/oauth/oauth_clients/edit.html.erb
<h1>Edit your application</h1>
<%= form_for  @client_application, :url => oauth_client_path(@client_application), :html => {:method => :put}  do |f| %>
       <%= render :partial => "form", :locals => { :f => f } %>
       <%= submit_tag "Edit" %>
<% end %>
<%= link_to 'Show', oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>

app/views/oauth/oauth_clients/index.html.erb
<div class="flash"><%= flash[:notice] %></div>
<h1>OAuth Client Applications</h1>
<% unless @tokens.empty? %>
<p>The following tokens have been issued to applications in your name</p>
<table class="table">
  <tr><th>Application</th><th>Issued</th><th>&nbsp;</th></tr>
  <% @tokens.each do |token|%>
    <% content_tag_for :tr, token do %>
      <td><%= link_to token.client_application.name, token.client_application.url %></td>
      <td><%= token.authorized_at %></td>
      <td>
        <% form_tag :controller => 'oauth', :action => 'revoke' do %>
        <%= hidden_field_tag 'token', token.token %>
        <%= submit_tag "Revoke!" %>
        <% end %>
      </td>
    <% end %>
  <% end %>

</table>
<% end %>
<% if @client_applications.empty? %>
  <p>
    Do you have an application you would like to register for use with us using the <a href="http://oauth.net">OAuth</a> standard?
  </p>
  <p>
    You must register your web application before it can make OAuth requests to this service
  </p>
<% else %>
  <p>
    You have the following client applications registered:
  </p>
  <table class="table table-striped">
    <tr><th>Third Party Application</th><th>Actions</th></tr>

    <% @client_applications.each do |client|%>
      <tr>
        <td><%= client.name %></td>
          <td>
            <%= link_to 'Details', oauth_client_path(client) %> |
            <%= link_to 'Edit', edit_oauth_client_path(client) %> |
            <%= link_to 'Delete', oauth_client_path(client), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% end %>
<br />
<h3><%= link_to "Register your application", :action => :new %></h3>

app/views/oauth/oauth_clients/new.html.erb
<h1>Register a new application</h1>
<%= form_for :client_application, :url => { :action => :create } do |f| %>
   <%= render :partial => "form", :locals => { :f => f } %>
   <%= submit_tag "Register" %>
<% end %>

app/views/oauth/oauth_clients/show.html.erb
<h1>OAuth details for <%=@client_application.name %></h1>
<hr/>
<p>
  <img src='<%=@client_application.logo.small %>' />
</p>
<p>
  <strong>Webhook URL:</strong>
  <code><%=@client_application.webhook_url %></code>
</p>
<p>
  <strong>Cancel URL:</strong>
  <code><%=@client_application.cancel_url %></code>
</p>
<p>
  <strong>Use Cancel URL:</strong>
  <code><%=@client_application.use_cancel_callback %></code>
</p>
<p>
  <strong>Delete third party profile deep link:</strong>
  <code><%=@client_application.delete_user_profile_deep_link %></code>
</p>
<hr/>
<p>
  <strong>Consumer Key:</strong>
  <code><%=@client_application.key %></code>
</p>
<p>
  <strong>Consumer Secret:</strong>
  <code><%=@client_application.secret %></code>
</p>
<p>
  <strong>Request Token URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.request_token_path %></code>
</p>
<p>
  <strong>Access Token URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.access_token_path %></code>
</p>
<p>
  <strong>Authorize URL</strong>
  <code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.authorize_path %></code>
</p>

<p>
  We support hmac-sha1 (recommended) as well as plain text in ssl mode.
</p>
<%= link_to 'Edit', edit_oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>